apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
    tier: backend
spec:
  ports:
    - protocol: TCP
      port: 3443
      targetPort: http
    # - protocol: TCP
    #   port: 443
    #   targetPort: https
  selector:
    app: api
    tier: backend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 2
  template:
    metadata:
      labels:
        app: api
        tier: backend
    spec:
      containers:
      - name: master
        image: <container-blob>/davinci-api:latest  # or just image: redis
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 3443
          # - name: https
          #   containerPort: 443
        env:
        - name: NODE_ENV
          value: "production"
        - name: NODE_INSPECT_BRK
          value: "false"
        - name: DAVINCI_PORT
          value: "3443"
        - name: DAVINCI_SECRET
          value: ${DAVINCI_SECRET}
        - name: DAVINCI_VERSION
          value: ${CI_COMMIT_SHA}
        - name: DAVINCI_AUTH_COOKIE
          value: "dvauth"
        - name: DAVINCI_RECAPTCHA_SECRET
          value: ${DAVINCI_RECAPTCHA_SECRET}
        - name: DAVINCI_DB_USERNAME
          value: ${DAVINCI_DB_USERNAME}
        - name: DAVINCI_DB_PASSWORD
          value: ${DAVINCI_DB_PASSWORD}
        - name: DAVINCI_DB_NAME
          value: ${DAVINCI_DB_NAME}
        - name: DAVINCI_DB_URL
          value: ${DAVINCI_DB_URL}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
    tier: backend
    role: master
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
    # - protocol: TCP
    #   port: 443
    #   targetPort: https
  selector:
    app: nginx
    tier: backend
    role: master
  type: LoadBalancer
  externalTrafficPolicy: Local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: <cointainer-blob>/davinci-nginx:latest
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 80
          # - name: https
          #   containerPort: 443

