/* eslint-disable no-param-reassign */
import _ from 'lodash';

// ISO 639-1 languages
const languages = {
  en: 'English',
  es: 'Español',
  pt: 'Português',
  de: 'Deutsch',
  aa: 'Afaraf',
  ab: 'аҧсуа бызшәа, аҧсшәа',
  ae: 'avesta',
  af: 'Afrikaans',
  ak: 'Akan',
  am: 'አማርኛ',
  an: 'aragonés',
  ar: 'العربية',
  as: 'অসমীয়া',
  av: 'авар мацӀ, магӀарул мацӀ',
  ay: 'aymar aru',
  az: 'azərbaycan dili',
  ba: 'башҡорт теле',
  be: 'беларуская мова',
  bg: 'български език',
  bh: 'भोजपुरी',
  bi: 'Bislama',
  bm: 'bamanankan',
  bn: 'বাংলা',
  bo: 'བོད་ཡིག',
  br: 'brezhoneg',
  bs: 'bosanski jezik',
  ca: 'català, valencià',
  ce: 'нохчийн мотт',
  ch: 'Chamoru',
  co: 'corsu, lingua corsa',
  cr: 'ᓀᐦᐃᔭᐍᐏᐣ',
  cs: 'čeština, český jazyk',
  cu: 'ѩзыкъ словѣньскъ',
  cv: 'чӑваш чӗлхи',
  cy: 'Cymraeg',
  da: 'dansk',
  dv: 'ދިވެހި',
  dz: 'རྫོང་ཁ',
  ee: 'Eʋegbe',
  el: 'ελληνικά',
  eo: 'Esperanto',
  et: 'eesti, eesti keel',
  eu: 'euskara, euskera',
  fa: 'فارسی',
  ff: 'Fulfulde, Pulaar, Pular',
  fi: 'suomi, suomen kieli',
  fj: 'vosa Vakaviti',
  fo: 'føroyskt',
  fr: 'français, langue française',
  fy: 'Frysk',
  ga: 'Gaeilge',
  gd: 'Gàidhlig',
  gl: 'Galego',
  gn: "Avañe'ẽ",
  gu: 'ગુજરાતી',
  gv: 'Gaelg, Gailck',
  ha: '(Hausa) هَوُسَ',
  he: 'עברית',
  hi: 'हिन्दी, हिंदी',
  ho: 'Hiri Motu',
  hr: 'hrvatski jezik',
  ht: 'Kreyòl ayisyen',
  hu: 'magyar',
  hy: 'Հայերեն',
  hz: 'Otjiherero',
  ia: 'Interlingua',
  id: 'Bahasa Indonesia',
  ie: 'Originally called Occidental; then Interlingue after WWII',
  ig: 'Asụsụ Igbo',
  ii: 'ꆈꌠ꒿ Nuosuhxop',
  ik: 'Iñupiaq, Iñupiatun',
  io: 'Ido',
  is: 'Íslenska',
  it: 'Italiano',
  iu: 'ᐃᓄᒃᑎᑐᑦ',
  ja: '日本語 (にほんご)',
  jv: 'ꦧꦱꦗꦮ, Basa Jawa',
  ka: 'ქართული',
  kg: 'Kikongo',
  ki: 'Gĩkũyũ',
  kj: 'Kuanyama',
  kk: 'қазақ тілі',
  kl: 'kalaallisut, kalaallit oqaasii',
  km: 'ខ្មែរ, ខេមរភាសា, ភាសាខ្មែរ',
  kn: 'ಕನ್ನಡ',
  ko: '한국어',
  kr: 'Kanuri',
  ks: 'कश्मीरी, كشميري‎',
  ku: 'Kurdî, کوردی‎',
  kv: 'коми кыв',
  kw: 'Kernewek',
  ky: 'Кыргызча, Кыргыз тили',
  la: 'latine, lingua latina',
  lb: 'Lëtzebuergesch',
  lg: 'Luganda',
  li: 'Limburgs',
  ln: 'Lingála',
  lo: 'ພາສາລາວ',
  lt: 'lietuvių kalba',
  lu: 'Kiluba',
  lv: 'latviešu valoda',
  mg: 'fiteny malagasy',
  mh: 'Kajin M̧ajeļ',
  mi: 'te reo Māori',
  mk: 'македонски јазик',
  ml: 'മലയാളം',
  mn: 'Монгол хэл',
  mr: 'मराठी',
  ms: 'Bahasa Melayu, بهاس ملايو‎',
  mt: 'Malti',
  my: 'ဗမာစာ',
  na: 'Dorerin Naoero',
  nb: 'Norsk Bokmål',
  nd: 'isiNdebele',
  ne: 'नेपाली',
  ng: 'Owambo',
  nl: 'Nederlands, Vlaams',
  nn: 'Norsk Nynorsk',
  no: 'Norsk',
  nr: 'isiNdebele',
  nv: 'Diné bizaad',
  ny: 'chiCheŵa, chinyanja',
  oc: "occitan, lenga d'òc",
  oj: 'ᐊᓂᔑᓈᐯᒧᐎᓐ',
  om: 'Afaan Oromoo',
  or: 'ଓଡ଼ିଆ',
  os: 'ирон æвзаг',
  pa: 'ਪੰਜਾਬੀ',
  pi: 'पाऴि',
  pl: 'język polski, polszczyzna',
  ps: 'پښتو',
  qu: 'Runa Simi, Kichwa',
  rm: 'Rumantsch Grischun',
  rn: 'Ikirundi',
  ro: 'Română',
  ru: 'русский',
  rw: 'Ikinyarwanda',
  sa: 'संस्कृतम्',
  sc: 'sardu',
  sd: 'सिन्धी, سنڌي، سندھی‎',
  se: 'Davvisámegiella',
  sg: 'yângâ tî sängö',
  si: 'සිංහල',
  sk: 'Slovenčina, Slovenský Jazyk',
  sl: 'Slovenski Jezik, Slovenščina',
  sm: "gagana fa'a Samoa",
  sn: 'chiShona',
  so: 'Soomaaliga, af Soomaali',
  sq: 'Shqip',
  sr: 'српски језик',
  ss: 'SiSwati',
  st: 'Sesotho',
  su: 'Basa Sunda',
  sv: 'Svenska',
  sw: 'Kiswahili',
  ta: 'தமிழ்',
  te: 'తెలుగు',
  tg: 'тоҷикӣ, toçikī, تاجیکی‎',
  th: 'ไทย',
  ti: 'ትግርኛ',
  tk: 'Türkmen, Түркмен',
  tl: 'Wikang Tagalog',
  tn: 'Setswana',
  to: 'Faka Tonga',
  tr: 'Türkçe',
  ts: 'Xitsonga',
  tt: 'татар теле, tatar tele',
  tw: 'Twi',
  ty: 'Reo Tahiti',
  ug: 'ئۇيغۇرچە‎, Uyghurche',
  uk: 'Українська',
  ur: 'اردو',
  uz: 'Oʻzbek, Ўзбек, أۇزبېك‎',
  ve: 'Tshivenḓa',
  vi: 'Tiếng Việt',
  vo: 'Volapük',
  wa: 'Walon',
  wo: 'Wollof',
  xh: 'isiXhosa',
  yi: 'ייִדיש',
  yo: 'Yorùbá',
  za: 'Saɯ cueŋƅ, Saw cuengh',
  zh: '中文 (Zhōngwén), 汉语, 漢語',
  zu: 'isiZulu'
};

const knownLanguages = _.pick(languages, ['en', 'es']);

const computeLanguageList = countriesObj => _.map(_.keys(countriesObj), key => ({
  value: key,
  name: countriesObj[key]
}));

const _state = {
  languages,
  languageList: computeLanguageList(knownLanguages),
  allLanguages: computeLanguageList(languages)
};

const getters = {
  languages: storeState => storeState.languages,
  languageList: storeState => storeState.languageList,
  allLanguages: storeState => storeState.allLanguages
};

export default {
  state: _state,
  getters,
  mutations: {},
  actions: {},
  namespaced: true
};
